apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-store-service
  labels:
    app: my-store-service
spec:
  replicas: 2 # 미니 PC 사양을 고려해 2개 정도 띄웁니다.
  selector:
    matchLabels:
      app: my-store-service
  template:
    metadata:
      labels:
        app: my-store-service
    spec:
      containers:
        - name: my-store-service
          image: jaehyun1217/my-store-service:151ccc3
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: my-store-service-svc
spec:
  selector:
    app: my-store-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP #ingress 설정 완료로 Nodeport 에서 ClusterIP 로 수정